### ISSUE TITLE
Containerise Tania with Docker

### ISSUE THREAD

**Issue by bepitulaz** [Tanibox/tania-core#39]
To make Tania easier to install, it will be better if we can containerise Tania. Hence, the user can install it with less hassle on the various device that supports Docker. Please, help me to do that. Thank you.

Note: Put the `dockerfile` on the master branch. The `2.0.0-dev` branch will follow it.

**Comment by hbakhtiyor** [comment]
any reasons why need docker? since there are no any dependencies and it's single executable file already

**Comment by bepitulaz** [comment]
The consideration is for users that want try to install Tania on the machine that supports Docker but we don't provide the binary for that architecture such as ARM-based network attached storage, Raspberry Pi, etc. Then the user can build the source from the Docker container and run it easily.

Do you have any suggestion?

**Comment by hbakhtiyor** [comment]
what do you think about https://github.com/goreleaser/goreleaser

**Comment by bepitulaz** [comment]
Wow, I just know it. Thank you. It seems perfect. I'll try it.

**Comment by bepitulaz** [comment]
I close this issue. Let us go to the Tania v2.0 development first, then we can decide between Docker or Goreleaser.

**Comment by gucharbon** [comment]
Sorry to comment on this closed issue, but I wanted to add my two cents as someone who is neither a javascript developer nor a go developer.

> Note: I found your project while taking a look at [Awesome self hosted](https://github.com/awesome-selfhosted/awesome-selfhosted#resource-planning) 

Your Readme convinced me to try out your software :) But then I found out that I needed to:

- Visit your website
- Subscribe to a newsletter
- Visit my mail box
- Visit your Google Drive account :open_mouth: ?
- Download the binary from your Google Drive account

IMHO this is not encouraging people to try out your product... At least it almost made me quit when I saw the Google Drive... This lead to my to my fisr question:  **Why did you stop hosting your binary release on GitHub ?** I get that you want to collect some emails so that you can better understand the adoption of tania, but this could totally be included in the app through a banner or a form on first startup of the tool.

Anyway, I can now run tania. I simply edit the `config.json` :grinning: ... Well no, I don't have `glibc 2.28` installed on my computer, I only have 2.27 :face_with_head_bandage:
``` bash
version `GLIBC_2.28' not found (required by ./tania-core)
```
At this point, I quit and will not waste more time for a project that should "Just Works™"

I wish I could to a simple `docker run -it --rm --name=tania-demo -p 8080:8080 tanibox/tania-core` to try it out, and would be more than happy to spend more time if this is the right tool for me.

I hope you don't take this post as aggressive and I know that while your project is open source it does not mean that you must do everything we ask of you. I just hope that this post will make you recognize the necessity of having a docker image, even if it's not production ready.

**Comment by nullinger** [comment]
👍 Docker

**Comment by bepitulaz** [comment]
Hi @gucharbon, you are correct. I did want to collect the email, but now I removed that from the site since few weeks ago (not yet to move the binary back to Github anyway). Thanks for your email collection suggestion. Really appreciate it, I didn't think that way actually, but that sounds really good :)
